import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatCardModule,
  MatTabsModule,
  MatToolbarModule,
  MatIconModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatFormFieldModule,
  MatCheckboxModule,
  MatSelectModule,
  MatDialogModule,
  MatRadioModule,
  MatSidenavModule,
  MatInputModule,
  MatSnackBarModule,
  MatChipsModule,
  MatTreeModule,
  MatBottomSheetModule,
  MatTooltipModule,
  MatDividerModule,
  MatDatepickerModule,
  MAT_DATE_LOCALE,
  MatNativeDateModule,
  MatSlideToggleModule,
} from '@angular/material';


@NgModule({
  imports: [
    MatButtonModule,
    MatCardModule,
    MatTabsModule,
    MatToolbarModule,
    MatIconModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatSelectModule,
    MatDialogModule,
    MatRadioModule,
    MatSidenavModule,
    MatInputModule,
    MatSnackBarModule,
    MatChipsModule,
    MatTreeModule,
    MatBottomSheetModule,
    MatTooltipModule,
    MatDividerModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
  ],
  exports: [
    MatButtonModule,
    MatCardModule,
    MatTabsModule,
    MatToolbarModule,
    MatIconModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatSelectModule,
    MatDialogModule,
    MatRadioModule,
    MatSidenavModule,
    MatInputModule,
    MatSnackBarModule,
    MatChipsModule,
    MatTreeModule,
    MatBottomSheetModule,
    MatTooltipModule,
    MatDividerModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
  ]
})
export class MaterialModule {}

